version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: schedule_postgres
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: schedule_user
      POSTGRES_PASSWORD: schedule_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - schedule_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: schedule_api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://schedule_user:schedule_password@postgres:5432/schedule_db
      PORT: 3001
      JWT_SECRET: your-jwt-secret-change-in-production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - schedule_network

volumes:
  postgres_data:

networks:
  schedule_network:
    driver: bridge